In [1]:
%matplotlib inline
import numpy as np
import scipy
from scipy.sparse import coo_matrix, csr_matrix, csc_matrix, block_diag, identity, hstack
import matplotlib.pyplot as plt
from pyiga import assemble, bspline, vform, geometry,vis, solvers, utils, topology, algebra, quadrature
#from sksparse.cholmod import cholesky
from pyiga import adaptive as adap
import itertools
import time
import statistics as st
from pyiga import algebra_cy, assemble_cy

np.set_printoptions(linewidth=100000)
np.set_printoptions(precision=5)
np.set_printoptions(formatter={'float_kind':"{:.3f}".format})

In [99]:
MP.mesh.draw(knots=1, nodes=1, patch_idx=1)

NameError: name 'MP' is not defined

In [4]:
#MP.h_refine({2:None})
for i in range(9):
    MP.h_refine(-1)
    print(MP.numdofs)

Refinement took 0.0015304088592529297 seconds for 6 patches.
setting up constraints took 0.03286099433898926 seconds.
Basis setup took 0.01323556900024414 seconds
682
Refinement took 0.0005130767822265625 seconds for 6 patches.
setting up constraints took 0.025909900665283203 seconds.
Basis setup took 0.009998798370361328 seconds
2376
Refinement took 0.0003998279571533203 seconds for 6 patches.
setting up constraints took 0.026726484298706055 seconds.
Basis setup took 0.010077714920043945 seconds
8836
Refinement took 0.0003135204315185547 seconds for 6 patches.
setting up constraints took 0.02816462516784668 seconds.
Basis setup took 0.01588273048400879 seconds
34044
Refinement took 0.00031685829162597656 seconds for 6 patches.
setting up constraints took 0.0475919246673584 seconds.
Basis setup took 0.0514070987701416 seconds
133612
Refinement took 0.00036716461181640625 seconds for 6 patches.
setting up constraints took 0.09637928009033203 seconds.
Basis setup took 0.16725707054138184

In [14]:
%timeit algebra_cy.pyx_compute_basis(*MP.Constr.shape, MP.Constr, maxiter=10)
%timeit algebra.compute_basis(MP.Constr, maxiter=10)

230 ms ± 7.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
531 ms ± 1.39 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
Constr = scipy.sparse.csr_matrix(np.array([[1,-1,0,0],[1,0,-0.5,-0.5],[0,1,-0.5,-0.5]]))

In [5]:
Constr.toarray()

array([[1.000, -1.000, 0.000, 0.000],
       [1.000, 0.000, -0.500, -0.500],
       [0.000, 1.000, -0.500, -0.500]])

In [8]:
Basis = algebra_cy.pyx_compute_basis(*Constr.shape,Constr,maxiter=10)

In [10]:
Basis.toarray()

array([[0.500, 0.500],
       [0.500, 0.500],
       [1.000, 0.000],
       [0.000, 1.000]])

In [13]:
MP.R_skeleton.T

<COOrdinate sparse matrix of dtype 'float64'
	with 142 stored elements and shape (270, 142)>

In [22]:
MP.Basis

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 303 stored elements and shape (270, 219)>

In [21]:
scipy.sparse.hstack([MP.R_interior.T, MP.R_skeleton.T@MP.R_skeleton@MP.Basis])

<COOrdinate sparse matrix of dtype 'float64'
	with 303 stored elements and shape (270, 347)>

In [10]:
def Heat_annulus(deg, N):
    kvs = [2 * (bspline.make_knots(deg, 0.0, 1.0, N),)]

    # define geometry
    geos = [
        geometry.quarter_annulus(),
    ]

    patches = [(k, g) for k, g in zip(kvs,geos)]
    M = topology.PatchMesh(patches)

    M.h_refine()

    M.set_domain_id({1:{0}})
    return M

In [19]:
M = Heat_annulus(1,2)

In [20]:
MP = assemble.Multipatch(M, automatch=True)

setting up constraints took 0.014943361282348633 seconds.
Basis setup took 0.004260540008544922 seconds


In [34]:
P2G = assemble_cy.pyx_right_inverse_C0_Basis(MP.Basis.indptr, MP.Basis.indices, MP.Basis.data, *MP.Basis.shape)

In [36]:
(P2G@MP.Basis).toarray()

array([[1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 1.000, 0.000, 0.000, 0.000, 0.000, 0.

In [30]:
MP.P2G

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 36 stored elements and shape (25, 36)>

In [31]:
MP.Basis

<Compressed Sparse Column sparse matrix of dtype 'float64'
	with 36 stored elements and shape (36, 25)>

In [32]:
MP.P2G

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 36 stored elements and shape (25, 36)>

In [300]:
p=5
kv = bspline.make_knots(p,0,1,10)
h = kv.meshsize_avg()

In [301]:
derivs = scipy.sparse.vstack(bspline.collocation_derivs(kv, np.array([0],dtype=float), p))
derivs = scipy.sparse.spdiags([np.array([h**(i) for i in range(p+1)])],np.array([0]))@ derivs
oddderivs = range(1,p+1,2)
evenderivs = range(0,p,2)

In [302]:
C = derivs[evenderivs,:]

In [303]:
C.toarray()

array([[1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [20.000, -30.000, 10.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [120.000, -225.000, 141.667, -41.667, 5.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]])

In [306]:
B = algebra_cy.pyx_compute_basis(len(nodes),kv.numdofs,C,20)

In [307]:
(C@B).toarray()

array([[0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [66.667, -41.667, 5.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]])

In [308]:
B = algebra_cy.pyx_compute_basis(len(nodes),kv.numdofs,C@B,20)

AssertionError: Unable to derive further dofs.

In [102]:
C = bspline.collocation(kv,nodes)

In [103]:
C.toarray()

array([[0.000, 1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.500, 0.500, 0.000, 0.000]])

In [93]:
np.linalg.matrix_rank(C.toarray())

np.int64(2)

In [94]:
B = algebra_cy.pyx_compute_basis(len(nodes),kv.numdofs,C,5)

In [95]:
C.toarray()

array([[0.600, 0.400, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 1.000, 0.000]])

In [96]:
B.toarray()

array([[-0.667, 0.000, 0.000],
       [1.000, 0.000, 0.000],
       [0.000, 1.000, 0.000],
       [0.000, 0.000, 0.000],
       [0.000, 0.000, 1.000]])

In [97]:
(B).toarray()

array([[-0.667, 0.000, 0.000],
       [1.000, 0.000, 0.000],
       [0.000, 1.000, 0.000],
       [0.000, 0.000, 0.000],
       [0.000, 0.000, 1.000]])

In [98]:
(C@B).toarray()

array([[0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000]])

AttributeError: module 'scipy.sparse.linalg' has no attribute 'nullspace'